name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # At 02:00 on Monday

jobs:
  test:
    name: Test
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14, 16, 18]
        include:
          - os: windows-latest
            node-version: 16 # LTS
          - os: macos-latest
            node-version: 16 # LTS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test --ignore-scripts
